version: '3.0'
services:

  webserver:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./wwwroot:/var/www
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - /etc/letsencrypt:/etc/letsencrypt